"""
Pytest tests for jordan_form_sympy_exact.py.

Run:
    pip install pytest sympy
    pytest -q

Expected project structure:
    jordan_form_sympy_exact.py
    test_jordan_form_sympy_exact.py

These tests intentionally do not use eigenvals/eigenvects/jordan_form/SVD.
They verify the implemented Jordan algorithm through exact identities:
    A * P == P * J
    det(P) != 0
    characteristic polynomials agree
    recovered Jordan block structure matches the expected one
"""

import pytest
import sympy as sp

from main import (
    jordan_form_exact,
    make_jordan_matrix,
    random_unimodular_matrix,
    same_jordan_structure,
    algebraic_roots_with_multiplicities,
    jordan_block_sizes,
)


# =========================================================
# Helpers
# =========================================================


def assert_zero_matrix(M):
    M = sp.simplify(M)
    assert M == sp.zeros(M.rows, M.cols)



def assert_valid_jordan_decomposition(A, J, P):
    """
    Checks the main contract:
        A * P = P * J
        det(P) != 0
    """
    A = sp.Matrix(A)
    J = sp.Matrix(J)
    P = sp.Matrix(P)

    assert P.det() != 0
    assert_zero_matrix(A * P - P * J)



def expected_structure_from_block_specs(block_specs):
    """
    Converts [(lambda, size), ...] into
    [(lambda, [sizes...]), ...]
    """
    result = []

    for lam, size in block_specs:
        inserted = False
        for i, (old_lam, sizes) in enumerate(result):
            if sp.simplify(old_lam - lam) == 0:
                sizes.append(size)
                inserted = True
                break

        if not inserted:
            result.append((lam, [size]))

    for _, sizes in result:
        sizes.sort(reverse=True)

    result.sort(key=lambda item: str(item[0]))
    return result



def structure_from_J(J):
    """
    Extracts Jordan block structure directly from a Jordan matrix J.

    Assumes standard Jordan form with eigenvalues on diagonal and ones
    on the superdiagonal inside blocks.
    """
    J = sp.Matrix(J)
    n = J.rows
    result = []
    i = 0

    while i < n:
        lam = sp.simplify(J[i, i])
        size = 1

        while i + size < n and sp.simplify(J[i + size - 1, i + size]) == 1:
            if sp.simplify(J[i + size, i + size] - lam) != 0:
                break
            size += 1

        found = False
        for idx, (old_lam, sizes) in enumerate(result):
            if sp.simplify(old_lam - lam) == 0:
                sizes.append(size)
                found = True
                break

        if not found:
            result.append((lam, [size]))

        i += size

    for _, sizes in result:
        sizes.sort(reverse=True)

    result.sort(key=lambda item: str(item[0]))
    return result



def run_generated_case(block_specs, seed=0):
    """
    Generates exact test matrix:
        A = P0 * J0 * P0^{-1},
    where P0 is unimodular.
    Then verifies recovered J and P.
    """
    J0 = make_jordan_matrix(block_specs)
    P0 = random_unimodular_matrix(J0.rows, seed=seed)
    A = sp.simplify(P0 * J0 * P0.inv())

    J, P, recovered_structure = jordan_form_exact(A)

    expected_structure = expected_structure_from_block_specs(block_specs)

    assert_valid_jordan_decomposition(A, J, P)
    assert same_jordan_structure(expected_structure, recovered_structure)
    assert same_jordan_structure(expected_structure, structure_from_J(J))

    # Similar matrices have the same characteristic polynomial.
    t = sp.Symbol("x")
    assert sp.factor(A.charpoly(t).as_expr() - J.charpoly(t).as_expr()) == 0


# =========================================================
# Step 1: necessary correctness situations
# =========================================================

"""
We test the following situations:

1. Diagonalizable matrices with distinct integer eigenvalues.
2. Diagonalizable matrices with irrational algebraic eigenvalues.
3. A nilpotent matrix with one maximal Jordan block J_n(0).
4. A matrix with one maximal Jordan block J_n(lambda), lambda != 0.
5. Several Jordan blocks for the same eigenvalue.
6. Mixed spectrum: integer and algebraic irrational eigenvalues.
7. Matrices not initially in Jordan form, generated by A = PJP^{-1}.
8. Correct recovery of characteristic roots and multiplicities.
9. Correct recovery of block sizes from defects dim Ker((A-lambda I)^k).
10. Generator correctness: random_unimodular_matrix must have determinant +-1.
"""


# =========================================================
# Basic Jordan decomposition tests
# =========================================================


def test_diagonalizable_distinct_integer_eigenvalues():
    block_specs = [(1, 1), (2, 1), (3, 1)]
    run_generated_case(block_specs, seed=1)



def test_diagonalizable_irrational_eigenvalues_sqrt2_pair():
    A = sp.Matrix([
        [0, 2],
        [1, 0],
    ])

    J, P, recovered_structure = jordan_form_exact(A)

    expected_structure = [(-sp.sqrt(2), [1]), (sp.sqrt(2), [1])]

    assert_valid_jordan_decomposition(A, J, P)
    assert same_jordan_structure(expected_structure, recovered_structure)
    assert same_jordan_structure(expected_structure, structure_from_J(J))



def test_nilpotent_one_maximal_block_j3_zero():
    block_specs = [(0, 3)]
    run_generated_case(block_specs, seed=2)



def test_one_maximal_block_j3_lambda_2():
    block_specs = [(2, 3)]
    run_generated_case(block_specs, seed=3)



def test_two_blocks_same_eigenvalue():
    block_specs = [(3, 2), (3, 1)]
    run_generated_case(block_specs, seed=4)



def test_mixed_integer_and_irrational_spectrum():
    block_specs = [(sp.sqrt(2), 1), (-sp.sqrt(2), 1), (3, 1)]
    run_generated_case(block_specs, seed=5)



def test_symbolic_jordan_block_for_sqrt2():
    # This matrix has entries in Q(sqrt(2)), not only integers.
    # It tests exact algebraic arithmetic and Jordan chains for algebraic lambda.
    block_specs = [(sp.sqrt(2), 2)]
    run_generated_case(block_specs, seed=6)


# =========================================================
# Direct tests for roots and block sizes
# =========================================================


def test_roots_with_multiplicities_integer_repeated():
    A = make_jordan_matrix([(2, 3), (-1, 2)])

    roots = algebraic_roots_with_multiplicities(A)
    expected = [(-1, 2), (2, 3)]

    assert len(roots) == len(expected)
    for (got_lam, got_mult), (exp_lam, exp_mult) in zip(roots, expected):
        assert sp.simplify(got_lam - exp_lam) == 0
        assert got_mult == exp_mult



def test_roots_with_multiplicities_irrational_pair():
    A = sp.Matrix([
        [0, 2],
        [1, 0],
    ])

    roots = algebraic_roots_with_multiplicities(A)
    expected = [(-sp.sqrt(2), 1), (sp.sqrt(2), 1)]

    assert len(roots) == len(expected)
    for (got_lam, got_mult), (exp_lam, exp_mult) in zip(roots, expected):
        assert sp.simplify(got_lam - exp_lam) == 0
        assert got_mult == exp_mult



def test_block_sizes_one_maximal_nilpotent_block():
    A = make_jordan_matrix([(0, 4)])
    sizes = jordan_block_sizes(A, 0, 4)
    assert sizes == [4]



def test_block_sizes_multiple_blocks_same_lambda():
    A = make_jordan_matrix([(5, 3), (5, 2), (5, 1)])
    sizes = jordan_block_sizes(A, 5, 6)
    assert sizes == [3, 2, 1]


# =========================================================
# Generator tests
# =========================================================


def test_random_unimodular_matrix_has_det_plus_minus_one():
    for seed in range(20):
        P = random_unimodular_matrix(5, seed=seed)
        assert abs(P.det()) == 1


@pytest.mark.parametrize(
    "block_specs,seed",
    [
        ([(0, 1)], 10),
        ([(0, 2)], 11),
        ([(1, 1), (2, 1)], 12),
        ([(2, 2), (2, 1)], 13),
        ([(3, 3), (-1, 1)], 14),
        ([(sp.sqrt(3), 1), (-sp.sqrt(3), 1)], 15),
    ],
)
def test_generated_cases_parametrized(block_specs, seed):
    run_generated_case(block_specs, seed=seed)


# =========================================================
# Negative / edge behavior
# =========================================================


def test_non_square_matrix_rejected():
    A = sp.Matrix([
        [1, 2, 3],
        [4, 5, 6],
    ])

    with pytest.raises(ValueError):
        jordan_form_exact(A)



def test_transition_matrix_is_invertible_for_recovered_decomposition():
    A = sp.Matrix([
        [0, 2],
        [1, 0],
    ])

    J, P, _ = jordan_form_exact(A)
    assert P.det() != 0
    assert_valid_jordan_decomposition(A, J, P)
